INFINITY = 2147483647
MAXFEEDITEMS = 7
MAXFEEDITEMSBYTYPE = 3

# Image
SUPPORTED_IMAGE_TYPES = ['jpeg', 'png', 'gif', 'jpg']
AVATAR_SIZE_LARGE  = '128x128'
AVATAR_SIZE_MEDIUM = '48x48'
AVATAR_SIZE_SMALL  = '32x32'

# Number of comments shown in a conversation
MAX_COMMENTS_IN_FEED = 25
COMMENTS_PER_PAGE = 25

#Number of people in one page
PEOPLE_PER_PAGE = 25
